[{
	"resource": "/c:/Users/jessi/Desktop/wetheparent-v4-app/components/DocumentsList.tsx",
	"owner": "typescript",
	"code": "2305",
	"severity": 8,
	"message": "Module '\"react\"' has no exported member 'useEffect'.",
	"source": "ts",
	"startLineNumber": 2,
	"startColumn": 10,
	"endLineNumber": 2,
	"endColumn": 19,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/jessi/Desktop/wetheparent-v4-app/components/DocumentsList.tsx",
	"owner": "typescript",
	"code": "2305",
	"severity": 8,
	"message": "Module '\"react\"' has no exported member 'useState'.",
	"source": "ts",
	"startLineNumber": 2,
	"startColumn": 21,
	"endLineNumber": 2,
	"endColumn": 29,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/jessi/Desktop/wetheparent-v4-app/components/DocumentsList.tsx",
	"owner": "typescript",
	"code": "7026",
	"severity": 8,
	"message": "JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.",
	"source": "ts",
	"startLineNumber": 39,
	"startColumn": 12,
	"endLineNumber": 39,
	"endColumn": 42,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/jessi/Desktop/wetheparent-v4-app/components/DocumentsList.tsx",
	"owner": "typescript",
	"code": "7026",
	"severity": 8,
	"message": "JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.",
	"source": "ts",
	"startLineNumber": 39,
	"startColumn": 74,
	"endLineNumber": 39,
	"endColumn": 80,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/jessi/Desktop/wetheparent-v4-app/components/DocumentsList.tsx",
	"owner": "typescript",
	"code": "7026",
	"severity": 8,
	"message": "JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.",
	"source": "ts",
	"startLineNumber": 43,
	"startColumn": 5,
	"endLineNumber": 43,
	"endColumn": 32,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/jessi/Desktop/wetheparent-v4-app/components/DocumentsList.tsx",
	"owner": "typescript",
	"code": "7026",
	"severity": 8,
	"message": "JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.",
	"source": "ts",
	"startLineNumber": 44,
	"startColumn": 7,
	"endLineNumber": 44,
	"endColumn": 60,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/jessi/Desktop/wetheparent-v4-app/components/DocumentsList.tsx",
	"owner": "typescript",
	"code": "7026",
	"severity": 8,
	"message": "JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.",
	"source": "ts",
	"startLineNumber": 44,
	"startColumn": 69,
	"endLineNumber": 44,
	"endColumn": 74,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/jessi/Desktop/wetheparent-v4-app/components/DocumentsList.tsx",
	"owner": "typescript",
	"code": "7026",
	"severity": 8,
	"message": "JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.",
	"source": "ts",
	"startLineNumber": 45,
	"startColumn": 7,
	"endLineNumber": 45,
	"endColumn": 38,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/jessi/Desktop/wetheparent-v4-app/components/DocumentsList.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'd' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 47,
	"startColumn": 21,
	"endLineNumber": 47,
	"endColumn": 22,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/jessi/Desktop/wetheparent-v4-app/components/DocumentsList.tsx",
	"owner": "typescript",
	"code": "7026",
	"severity": 8,
	"message": "JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.",
	"source": "ts",
	"startLineNumber": 47,
	"startColumn": 27,
	"endLineNumber": 47,
	"endColumn": 42,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/jessi/Desktop/wetheparent-v4-app/components/DocumentsList.tsx",
	"owner": "typescript",
	"code": "7026",
	"severity": 8,
	"message": "JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.",
	"source": "ts",
	"startLineNumber": 47,
	"startColumn": 55,
	"endLineNumber": 47,
	"endColumn": 60,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/jessi/Desktop/wetheparent-v4-app/components/DocumentsList.tsx",
	"owner": "typescript",
	"code": "7026",
	"severity": 8,
	"message": "JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.",
	"source": "ts",
	"startLineNumber": 49,
	"startColumn": 11,
	"endLineNumber": 49,
	"endColumn": 15,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/jessi/Desktop/wetheparent-v4-app/components/DocumentsList.tsx",
	"owner": "typescript",
	"code": "7026",
	"severity": 8,
	"message": "JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.",
	"source": "ts",
	"startLineNumber": 49,
	"startColumn": 48,
	"endLineNumber": 49,
	"endColumn": 53,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/jessi/Desktop/wetheparent-v4-app/components/DocumentsList.tsx",
	"owner": "typescript",
	"code": "7026",
	"severity": 8,
	"message": "JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.",
	"source": "ts",
	"startLineNumber": 51,
	"startColumn": 7,
	"endLineNumber": 51,
	"endColumn": 12,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/jessi/Desktop/wetheparent-v4-app/components/DocumentsList.tsx",
	"owner": "typescript",
	"code": "7026",
	"severity": 8,
	"message": "JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.",
	"source": "ts",
	"startLineNumber": 52,
	"startColumn": 5,
	"endLineNumber": 52,
	"endColumn": 11,
	"origin": "extHost1"
}]