# File: .github/workflows/ci.yml

name: Continuous Integration (CI)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    strategy:
      # Maximize cost-efficiency: Fail fast if the build or types break
      fail-fast: true 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build project and Type Check (CRITICAL)
        # Ensure the build succeeds and TypeScript has no errors
        run: npm run build
      
      - name: Run Unit Tests (Jest/Vitest)
        # These tests rely on the Supabase mock you created in Step 1.
        run: npm test

      # --- E2E TESTING SETUP (Zero-Cost Mock) ---
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run E2E Tests (Playwright)
        # These E2E tests run against the built application using mocks for external services.
        # This confirms that all feature interactions (e.g., streaming chat, drafting) are sound.
        run: npm run test:e2e

      # --- DEPLOYMENT PREP (Optional, but good for Vercel) ---
      - name: Archive Playwright test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7